import { DurableStore } from './durableStore';
import { HarnessAction, ApprovalPolicyService } from './approvalPolicyService';

export type AutonomyLevel = 'A_READ' | 'B_PLAN' | 'C_BRANCH' | 'D_VERIFY_REPAIR' | 'E_RELEASE_PREP' | 'F_APPROVED_DEPLOY';
export interface AutonomySession { id: string; tenantId: string; jobId?: string; level: AutonomyLevel; allowedActions: HarnessAction[]; maxSteps: number; stepsUsed: number; maxRetries: number; retriesUsed: number; maxCostUnits: number; costUsed: number; status: 'ACTIVE' | 'ESCALATED' | 'COMPLETED' | 'ABORTED'; createdAt: string; updatedAt: string; }
const levelActions: Record<AutonomyLevel, HarnessAction[]> = { A_READ: ['READ_REPOSITORY'], B_PLAN: ['READ_REPOSITORY'], C_BRANCH: ['READ_REPOSITORY', 'MODIFY_BRANCH'], D_VERIFY_REPAIR: ['READ_REPOSITORY', 'MODIFY_BRANCH', 'RUN_VERIFICATION'], E_RELEASE_PREP: ['READ_REPOSITORY', 'MODIFY_BRANCH', 'RUN_VERIFICATION', 'CREATE_PREVIEW'], F_APPROVED_DEPLOY: ['READ_REPOSITORY', 'MODIFY_BRANCH', 'RUN_VERIFICATION', 'CREATE_PREVIEW', 'DEPLOY_PRODUCTION'] };
export class AutonomyService {
  public static start(input: { tenantId: string; jobId?: string; level: AutonomyLevel; maxSteps?: number; maxRetries?: number; maxCostUnits?: number }): AutonomySession { const now = new Date().toISOString(); const session: AutonomySession = { id: DurableStore.id('autonomy', `${input.tenantId}:${input.jobId ?? ''}`), tenantId: input.tenantId, jobId: input.jobId, level: input.level, allowedActions: levelActions[input.level], maxSteps: Math.min(input.maxSteps ?? 20, 100), stepsUsed: 0, maxRetries: Math.min(input.maxRetries ?? 3, 5), retriesUsed: 0, maxCostUnits: Math.min(input.maxCostUnits ?? 100, 1000), costUsed: 0, status: 'ACTIVE', createdAt: now, updatedAt: now }; DurableStore.upsert('autonomySessions', session.id, session as unknown as Record<string, unknown>); return session; }
  public static consume(tenantId: string, id: string, action: HarnessAction, costUnits = 1): AutonomySession { const session = this.get(tenantId, id); if (!session) throw new Error('AUTONOMY_SESSION_NOT_FOUND'); if (session.status !== 'ACTIVE') throw new Error('AUTONOMY_SESSION_NOT_ACTIVE'); if (!session.allowedActions.includes(action)) throw new Error(`AUTONOMY_ACTION_NOT_ALLOWED:${action}`); if (session.stepsUsed + 1 > session.maxSteps) throw new Error('AUTONOMY_STEP_BUDGET_EXCEEDED'); if (session.costUsed + costUnits > session.maxCostUnits) throw new Error('AUTONOMY_COST_BUDGET_EXCEEDED'); if (ApprovalPolicyService.requiresApproval(action) && action === 'DEPLOY_PRODUCTION') throw new Error('AUTONOMY_APPROVAL_REQUIRED:DEPLOY_PRODUCTION'); const updated = { ...session, stepsUsed: session.stepsUsed + 1, costUsed: session.costUsed + costUnits, updatedAt: new Date().toISOString() }; DurableStore.upsert('autonomySessions', id, updated as unknown as Record<string, unknown>); return updated; }
  public static abort(tenantId: string, id: string): AutonomySession { const session = this.get(tenantId, id); if (!session) throw new Error('AUTONOMY_SESSION_NOT_FOUND'); const updated = { ...session, status: 'ABORTED' as const, updatedAt: new Date().toISOString() }; DurableStore.upsert('autonomySessions', id, updated as unknown as Record<string, unknown>); return updated; }
  public static get(tenantId: string, id: string): AutonomySession | undefined { const session = DurableStore.get('autonomySessions', id) as unknown as AutonomySession | undefined; return session?.tenantId === tenantId ? session : undefined; }
  public static list(tenantId: string): AutonomySession[] { return DurableStore.list('autonomySessions').filter((item) => item.tenantId === tenantId) as unknown as AutonomySession[]; }
}
