import crypto from 'node:crypto';
import { DurableStore } from './durableStore';
import { FailureClass } from './verificationProfileService';

export type FailureDomain = FailureClass | 'SPECIFICATION' | 'DEPENDENCY' | 'ENVIRONMENT' | 'DEPLOYMENT' | 'RUNTIME_HEALTH' | 'PRODUCT_ADOPTION';
export type FailureStatus = 'OPEN' | 'CONTAINED' | 'RESOLVED' | 'ESCALATED';
export interface FailureRecord { id: string; tenantId: string; jobId?: string; domain: FailureDomain; fingerprint: string; message: string; nextAction: string; owner: string; retryBudget: number; retriesUsed: number; occurrences: number; status: FailureStatus; evidence: string[]; createdAt: string; updatedAt: string; }
const actionFor = (domain: FailureDomain): string => ({ SPECIFICATION: 'Clarify acceptance criteria and update the product brief', DEPENDENCY: 'Pin or repair the dependency and rerun verification', TYPECHECK: 'Repair the type or compile contract within the bounded loop', TEST: 'Fix the failing behavior or update an evidence-backed test', SECURITY: 'Contain the change and complete security review before retrying', ENVIRONMENT: 'Repair the project environment or request missing configuration', BUILD: 'Repair the build profile and rerun the artifact check', FORMAT: 'Apply formatting and rerun the profile', DEPLOYMENT: 'Stop release completion and inspect deployment output', RUNTIME_HEALTH: 'Rollback to the last healthy release and inspect runtime evidence', PRODUCT_ADOPTION: 'Interview the user or client and update the outcome record', UNKNOWN: 'Escalate for human diagnosis before another attempt' } as Record<FailureDomain, string>)[domain];
export class FailureService {
  public static record(input: { tenantId: string; jobId?: string; domain: FailureDomain; message: string; evidence?: string[]; retryBudget?: number; owner?: string }): FailureRecord {
    const fingerprint = crypto.createHash('sha256').update(`${input.tenantId}:${input.domain}:${input.message}`).digest('hex').slice(0, 20); const previous = DurableStore.list('failures').find((item) => item.tenantId === input.tenantId && item.fingerprint === fingerprint) as unknown as FailureRecord | undefined; const now = new Date().toISOString(); const record: FailureRecord = { id: previous?.id ?? DurableStore.id('failure', fingerprint), tenantId: input.tenantId, jobId: input.jobId, domain: input.domain, fingerprint, message: input.message, nextAction: actionFor(input.domain), owner: input.owner ?? 'founder', retryBudget: input.retryBudget ?? 3, retriesUsed: previous?.retriesUsed ?? 0, occurrences: (previous?.occurrences ?? 0) + 1, status: previous?.status === 'RESOLVED' ? 'OPEN' : previous?.status ?? 'OPEN', evidence: [...new Set([...(previous?.evidence ?? []), ...(input.evidence ?? [])])], createdAt: previous?.createdAt ?? now, updatedAt: now }; DurableStore.upsert('failures', record.id, record as unknown as Record<string, unknown>); return record;
  }
  public static retry(tenantId: string, id: string): FailureRecord { const record = this.get(tenantId, id); if (!record) throw new Error('FAILURE_NOT_FOUND'); const retriesUsed = record.retriesUsed + 1; const status: FailureStatus = retriesUsed > record.retryBudget ? 'ESCALATED' : 'CONTAINED'; const updated = { ...record, retriesUsed, status, updatedAt: new Date().toISOString() }; DurableStore.upsert('failures', id, updated as unknown as Record<string, unknown>); return updated; }
  public static resolve(tenantId: string, id: string, evidence: string): FailureRecord { const record = this.get(tenantId, id); if (!record) throw new Error('FAILURE_NOT_FOUND'); const updated = { ...record, status: 'RESOLVED' as const, evidence: [...new Set([...record.evidence, evidence])], updatedAt: new Date().toISOString() }; DurableStore.upsert('failures', id, updated as unknown as Record<string, unknown>); return updated; }
  public static get(tenantId: string, id: string): FailureRecord | undefined { const record = DurableStore.get('failures', id) as unknown as FailureRecord | undefined; return record?.tenantId === tenantId ? record : undefined; }
  public static list(tenantId: string): FailureRecord[] { return DurableStore.list('failures').filter((item) => item.tenantId === tenantId) as unknown as FailureRecord[]; }
}
