import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { DurableStore } from './durableStore';
import { WorkspaceService } from './workspaceService';

export type DeploymentProvider = 'filesystem-hosted' | 'webhook-hosted';
export interface HostedTarget { id: string; tenantId: string; projectId: string; provider: DeploymentProvider; endpoint?: string; secretRef?: string; artifactRoot: string; healthPath?: string; observationSeconds: number; createdAt: string; }
export interface HostedDeployment { id: string; tenantId: string; projectId: string; targetId: string; sourcePath: string; artifactPath: string; artifactChecksum: string; status: 'PREPARED' | 'DEPLOYED' | 'HEALTHY' | 'ROLLED_BACK' | 'FAILED'; health: { checkedAt: string; passed: boolean; detail: string }; previousDeploymentId?: string; createdAt: string; }

function checksum(file: string): string { return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'); }
function tenantOf(value: Record<string, unknown>): string { return String(value.tenantId ?? ''); }
function assertTarget(tenantId: string, targetId: string): HostedTarget { const target = DurableStore.get('hostedDeployments', targetId) as unknown as HostedTarget | undefined; if (!target || target.tenantId !== tenantId) throw new Error('HOSTED_TARGET_NOT_FOUND'); return target; }

export class HostedDeploymentService {
  public static registerTarget(input: { tenantId: string; projectId: string; provider?: DeploymentProvider; endpoint?: string; secretRef?: string; artifactRoot: string; healthPath?: string; observationSeconds?: number }): HostedTarget {
    if (!WorkspaceService.get(input.tenantId, input.projectId)) throw new Error('PROJECT_NOT_FOUND');
    if (input.provider === 'webhook-hosted' && (!input.endpoint || !input.secretRef)) throw new Error('HOSTED_TARGET_SECRET_REFERENCE_REQUIRED');
    const target: HostedTarget = { id: DurableStore.id('target', `${input.tenantId}:${input.projectId}:${input.artifactRoot}`), tenantId: input.tenantId, projectId: input.projectId, provider: input.provider ?? 'filesystem-hosted', endpoint: input.endpoint, secretRef: input.secretRef, artifactRoot: path.resolve(input.artifactRoot), healthPath: input.healthPath, observationSeconds: Math.min(Math.max(input.observationSeconds ?? 30, 1), 3600), createdAt: new Date().toISOString() };
    fs.mkdirSync(target.artifactRoot, { recursive: true, mode: 0o700 }); DurableStore.upsert('hostedDeployments', target.id, target as unknown as Record<string, unknown>); return target;
  }
  public static listTargets(tenantId: string): HostedTarget[] { return DurableStore.list('hostedDeployments').filter((item) => item.kind === undefined && tenantOf(item) === tenantId && item.artifactPath === undefined) as unknown as HostedTarget[]; }
  public static deploy(tenantId: string, targetId: string, sourcePath: string, input: { approved: boolean; sourceCommit: string }): HostedDeployment {
    const target = assertTarget(tenantId, targetId); if (!input.approved) throw new Error('HOSTED_DEPLOYMENT_APPROVAL_REQUIRED'); if (!fs.existsSync(sourcePath)) throw new Error('HOSTED_SOURCE_ARTIFACT_NOT_FOUND');
    const previous = this.listDeployments(tenantId).find((item) => item.projectId === target.projectId && ['HEALTHY', 'DEPLOYED'].includes(item.status)); const id = DurableStore.id('deployment', `${tenantId}:${targetId}:${input.sourceCommit}`); const artifactPath = path.join(target.artifactRoot, id); fs.cpSync(sourcePath, artifactPath, { recursive: true }); const fileForDigest = path.join(artifactPath, fs.readdirSync(artifactPath)[0] ?? '.'); const artifactChecksum = fs.existsSync(fileForDigest) && fs.statSync(fileForDigest).isFile() ? checksum(fileForDigest) : crypto.createHash('sha256').update(JSON.stringify(fs.readdirSync(artifactPath).sort())).digest('hex'); const now = new Date().toISOString(); const deployment: HostedDeployment = { id, tenantId, projectId: target.projectId, targetId, sourcePath, artifactPath, artifactChecksum, status: 'DEPLOYED', health: { checkedAt: now, passed: true, detail: 'Artifact accepted by hosted deployment adapter' }, previousDeploymentId: previous?.id, createdAt: now }; DurableStore.upsert('hostedDeployments', id, deployment as unknown as Record<string, unknown>); return deployment;
  }
  public static observe(tenantId: string, deploymentId: string, input: { passed: boolean; detail: string }): HostedDeployment { const deployment = this.getDeployment(tenantId, deploymentId); if (!deployment) throw new Error('HOSTED_DEPLOYMENT_NOT_FOUND'); const updated = { ...deployment, status: input.passed ? 'HEALTHY' as const : 'FAILED' as const, health: { checkedAt: new Date().toISOString(), passed: input.passed, detail: input.detail } }; DurableStore.upsert('hostedDeployments', deploymentId, updated as unknown as Record<string, unknown>); return updated; }
  public static rollback(tenantId: string, deploymentId: string): HostedDeployment { const deployment = this.getDeployment(tenantId, deploymentId); if (!deployment) throw new Error('HOSTED_DEPLOYMENT_NOT_FOUND'); if (!deployment.previousDeploymentId) throw new Error('HOSTED_ROLLBACK_TARGET_NOT_FOUND'); const target = assertTarget(tenantId, deployment.targetId); const previous = this.getDeployment(tenantId, deployment.previousDeploymentId); if (!previous) throw new Error('HOSTED_ROLLBACK_TARGET_NOT_FOUND'); const current = path.join(target.artifactRoot, `${deployment.id}-rolled-back`); fs.cpSync(previous.artifactPath, current, { recursive: true }); const updated = { ...deployment, status: 'ROLLED_BACK' as const, artifactPath: current, health: { checkedAt: new Date().toISOString(), passed: true, detail: `Rolled back to ${previous.id}` } }; DurableStore.upsert('hostedDeployments', deploymentId, updated as unknown as Record<string, unknown>); return updated; }
  public static getDeployment(tenantId: string, id: string): HostedDeployment | undefined { const value = DurableStore.get('hostedDeployments', id) as unknown as HostedDeployment | undefined; return value && value.artifactPath && value.tenantId === tenantId ? value : undefined; }
  public static listDeployments(tenantId: string): HostedDeployment[] { return DurableStore.list('hostedDeployments').filter((item) => item.artifactPath !== undefined && tenantOf(item) === tenantId) as unknown as HostedDeployment[]; }
}
