import { DurableStore } from './durableStore';
import { HostedDeploymentService, HostedDeployment } from './hostedDeploymentService';
import { FailureService } from './failureService';

export interface Observation { id: string; tenantId: string; deploymentId: string; status: 'RUNNING' | 'HEALTHY' | 'DEGRADED' | 'ROLLED_BACK'; checks: Array<{ url: string; passed: boolean; statusCode?: number; latencyMs?: number; detail: string }>; consecutiveFailures: number; windowSeconds: number; rollbackRecommended: boolean; startedAt: string; completedAt?: string; }
export class ObservationService {
  public static start(tenantId: string, deploymentId: string, input: { healthUrl: string; windowSeconds?: number; failureThreshold?: number }): Observation { const deployment = HostedDeploymentService.getDeployment(tenantId, deploymentId); if (!deployment) throw new Error('HOSTED_DEPLOYMENT_NOT_FOUND'); const record: Observation = { id: DurableStore.id('observation', deploymentId), tenantId, deploymentId, status: 'RUNNING', checks: [], consecutiveFailures: 0, windowSeconds: Math.min(Math.max(input.windowSeconds ?? 60, 1), 3600), rollbackRecommended: false, startedAt: new Date().toISOString() }; DurableStore.upsert('deploymentObservations', record.id, { ...record, healthUrl: input.healthUrl, failureThreshold: input.failureThreshold ?? 2 }); return record; }
  public static record(tenantId: string, observationId: string, input: { passed: boolean; detail: string; statusCode?: number; latencyMs?: number }): Observation { const current = DurableStore.get('deploymentObservations', observationId) as unknown as Observation & { healthUrl?: string; failureThreshold?: number } | undefined; if (!current || current.tenantId !== tenantId) throw new Error('OBSERVATION_NOT_FOUND'); const checks = [...current.checks, { url: current.healthUrl ?? '', passed: input.passed, statusCode: input.statusCode, latencyMs: input.latencyMs, detail: input.detail }]; const consecutiveFailures = input.passed ? 0 : current.consecutiveFailures + 1; const rollbackRecommended = consecutiveFailures >= (current.failureThreshold ?? 2); const updated = { ...current, checks, consecutiveFailures, rollbackRecommended, status: rollbackRecommended ? 'DEGRADED' as const : (input.passed ? 'HEALTHY' as const : 'RUNNING' as const), completedAt: rollbackRecommended ? new Date().toISOString() : undefined }; DurableStore.upsert('deploymentObservations', observationId, updated as unknown as Record<string, unknown>); if (!input.passed) FailureService.record({ tenantId, domain: 'RUNTIME_HEALTH', message: input.detail, evidence: [`observation:${observationId}`], retryBudget: rollbackRecommended ? 0 : 1 }); return updated; }
  public static rollback(tenantId: string, observationId: string): HostedDeployment { const current = DurableStore.get('deploymentObservations', observationId) as unknown as Observation | undefined; if (!current || current.tenantId !== tenantId) throw new Error('OBSERVATION_NOT_FOUND'); const deployment = HostedDeploymentService.rollback(tenantId, current.deploymentId); DurableStore.upsert('deploymentObservations', observationId, { ...current, status: 'ROLLED_BACK', completedAt: new Date().toISOString() }); return deployment; }
  public static list(tenantId: string): Observation[] { return DurableStore.list('deploymentObservations').filter((item) => item.tenantId === tenantId) as unknown as Observation[]; }
}
