import { DurableStore } from './durableStore';

export type OutcomeSignal = 'ADOPTION' | 'RETENTION' | 'TIME_SAVED' | 'REVENUE' | 'CLIENT_ACCEPTANCE' | 'USER_FEEDBACK' | 'DEFECT' | 'INCIDENT' | 'LEARNING';
export interface OutcomeRecord { id: string; tenantId: string; jobId: string; productName: string; signal: OutcomeSignal; value: number; unit: string; note: string; reusablePatterns: string[]; decisionsToAvoid: string[]; recordedAt: string; }
export class OutcomeService {
  public static record(input: { tenantId: string; jobId: string; productName: string; signal: OutcomeSignal; value: number; unit: string; note: string; reusablePatterns?: string[]; decisionsToAvoid?: string[] }): OutcomeRecord { if (!input.note.trim()) throw new Error('OUTCOME_NOTE_REQUIRED'); const record: OutcomeRecord = { id: DurableStore.id('outcome', `${input.tenantId}:${input.jobId}:${input.signal}`), tenantId: input.tenantId, jobId: input.jobId, productName: input.productName.trim(), signal: input.signal, value: input.value, unit: input.unit.trim(), note: input.note.trim(), reusablePatterns: input.reusablePatterns ?? [], decisionsToAvoid: input.decisionsToAvoid ?? [], recordedAt: new Date().toISOString() }; DurableStore.upsert('outcomes', record.id, record as unknown as Record<string, unknown>); return record; }
  public static list(tenantId: string): OutcomeRecord[] { return DurableStore.list('outcomes').filter((item) => item.tenantId === tenantId) as unknown as OutcomeRecord[]; }
  public static summary(tenantId: string) { const records = this.list(tenantId); return { records: records.length, products: new Set(records.map((record) => record.jobId)).size, timeSaved: records.filter((record) => record.signal === 'TIME_SAVED').reduce((sum, record) => sum + record.value, 0), defects: records.filter((record) => record.signal === 'DEFECT').reduce((sum, record) => sum + record.value, 0), incidents: records.filter((record) => record.signal === 'INCIDENT').reduce((sum, record) => sum + record.value, 0), reusablePatterns: [...new Set(records.flatMap((record) => record.reusablePatterns))], decisionsToAvoid: [...new Set(records.flatMap((record) => record.decisionsToAvoid))] }; }
}
