import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { DurableStore } from './durableStore';

export type AdapterKind = 'node' | 'python' | 'rust' | 'android' | 'static' | 'unknown';
export interface ProjectAdapter { id: string; tenantId: string; projectId: string; kind: AdapterKind; checks: string[]; artifactPath?: string; createdAt: string; }
export interface SecurityScan { id: string; tenantId: string; projectId?: string; status: 'PASSED' | 'BLOCKED'; findings: Array<{ rule: string; severity: 'HIGH' | 'MEDIUM' | 'LOW'; file: string; detail: string }>; scannedAt: string; }
function tenantOf(value: Record<string, unknown>): string { return String(value.tenantId ?? ''); }
function walk(root: string, limit = 5000): string[] { const result: string[] = []; const visit = (dir: string): void => { if (result.length >= limit) return; for (const entry of fs.readdirSync(dir, { withFileTypes: true })) { if (['.git', 'node_modules', 'dist', 'build', '.data'].includes(entry.name)) continue; const full = path.join(dir, entry.name); if (entry.isDirectory()) visit(full); else result.push(full); } }; visit(root); return result; }
export class QualityGateService {
  public static detect(tenantId: string, projectId: string, root: string): ProjectAdapter { const files = walk(root).map((file) => path.basename(file)); const kind: AdapterKind = files.includes('package.json') ? 'node' : files.includes('pyproject.toml') || files.includes('requirements.txt') ? 'python' : files.includes('Cargo.toml') ? 'rust' : files.includes('build.gradle') || files.includes('gradlew') ? 'android' : files.includes('index.html') ? 'static' : 'unknown'; const checks = kind === 'node' ? ['npm run lint', 'npm test', 'npm run build', 'secret-scan'] : kind === 'python' ? ['python -m compileall', 'pytest', 'secret-scan'] : kind === 'rust' ? ['cargo fmt --check', 'cargo test', 'cargo build --release', 'secret-scan'] : ['git diff --check', 'secret-scan']; const adapter: ProjectAdapter = { id: DurableStore.id('adapter', `${tenantId}:${projectId}`), tenantId, projectId, kind, checks, createdAt: new Date().toISOString() }; DurableStore.upsert('projectAdapters', adapter.id, adapter as unknown as Record<string, unknown>); return adapter; }
  public static scan(tenantId: string, root: string, projectId?: string): SecurityScan { const findings: SecurityScan['findings'] = []; for (const file of walk(root)) { if (!/\.(ts|tsx|js|jsx|py|rs|json|env|yml|yaml|toml)$/.test(file)) continue; const text = fs.readFileSync(file, 'utf8'); if (/(AKIA[0-9A-Z]{16}|BEGIN (RSA|OPENSSH|EC) PRIVATE KEY|ghp_[A-Za-z0-9]{20,}|sk-[A-Za-z0-9]{20,})/.test(text)) findings.push({ rule: 'secret-pattern', severity: 'HIGH', file, detail: 'Credential-like material detected' }); if (/password\s*[:=]\s*['"][^'"]+['"]|api[_-]?key\s*[:=]\s*['"][^'"]+['"]/.test(text) && !file.endsWith('.example')) findings.push({ rule: 'inline-secret', severity: 'HIGH', file, detail: 'Possible inline credential detected' }); } try { if (fs.existsSync(path.join(root, 'package-lock.json'))) execFileSync('npm', ['audit', '--package-lock-only', '--audit-level=high', '--json'], { cwd: root, stdio: 'pipe', timeout: 60000 }); } catch (error: any) { findings.push({ rule: 'dependency-audit', severity: 'MEDIUM', file: path.join(root, 'package-lock.json'), detail: String(error.stdout || error.message || 'Dependency audit failed').slice(0, 2000) }); } const record: SecurityScan = { id: DurableStore.id('scan', `${tenantId}:${root}`), tenantId, projectId, status: findings.some((item) => item.severity === 'HIGH') ? 'BLOCKED' : 'PASSED', findings, scannedAt: new Date().toISOString() }; DurableStore.upsert('securityScans', record.id, record as unknown as Record<string, unknown>); return record; }
  public static list(tenantId: string): SecurityScan[] { return DurableStore.list('securityScans').filter((item) => tenantOf(item) === tenantId) as unknown as SecurityScan[]; }
}
