import { Router, Request, Response } from 'express';
import { respondWithError } from '../../utils/respondWithError';
import { validateTenantRequest } from '../middleware/tenantAuth';
import { WorkspaceService } from '../../services/workspaceService';
import { FactoryJobService } from '../../services/factoryJobService';
import { ExecutionBoundaryService } from '../../services/executionBoundaryService';
import { ReleaseService } from '../../services/releaseService';
import { FailureService } from '../../services/failureService';
import { OutcomeService } from '../../services/outcomeService';
import { AutonomyService } from '../../services/autonomyService';

const router = Router();
const tenant = (req: Request): string => String(req.body?.tenantId || req.query.tenantId || req.headers['x-tenant-id']);
const fail = (res: Response, error: unknown) => respondWithError(res, error, 'WORKSPACE_OPERATION_FAILED');
router.get('/inbox', (req, res) => { if (!validateTenantRequest(req, res)) return; return res.json({ status: 'success', inbox: WorkspaceService.inbox(tenant(req)) }); });
router.get('/projects', (req, res) => { if (!validateTenantRequest(req, res)) return; return res.json({ status: 'success', projects: WorkspaceService.list(tenant(req)) }); });
router.post('/projects', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.status(201).json({ status: 'success', project: WorkspaceService.register({ ...req.body, tenantId: tenant(req) }) }); } catch (error: any) { return fail(res, error); } });
router.post('/projects/:id/lifecycle', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.json({ status: 'success', project: WorkspaceService.updateLifecycle(tenant(req), req.params.id, req.body.lifecycle) }); } catch (error: any) { return fail(res, error); } });
router.post('/backup', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.status(201).json({ status: 'success', backup: WorkspaceService.backup(tenant(req)) }); } catch (error: any) { return fail(res, error); } });
router.post('/restore/:backupId', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.json({ status: 'success', restore: WorkspaceService.restore(tenant(req), req.params.backupId) }); } catch (error: any) { return fail(res, error); } });
router.post('/jobs/:id/tasks', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.status(201).json({ status: 'success', job: FactoryJobService.addCompletionTask(tenant(req), req.params.id, req.body) }); } catch (error: any) { return fail(res, error); } });
router.post('/jobs/:id/tasks/:taskId', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.json({ status: 'success', job: FactoryJobService.updateCompletionTask(tenant(req), req.params.id, req.params.taskId, req.body.status, req.body.evidenceKinds) }); } catch (error: any) { return fail(res, error); } });
router.get('/jobs/:id/continuation', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.json({ status: 'success', report: FactoryJobService.continuationReport(tenant(req), req.params.id) }); } catch (error: any) { return fail(res, error); } });
router.post('/execution/manifest', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.status(201).json({ status: 'success', manifest: ExecutionBoundaryService.createManifest(tenant(req), req.body.sourcePath, req.body) }); } catch (error: any) { return fail(res, error); } });
router.post('/execution/:manifestId/run', (req, res) => { if (!validateTenantRequest(req, res)) return; try { const run = ExecutionBoundaryService.run(tenant(req), req.params.manifestId); return res.json({ status: 'success', run: { ...run, digest: ExecutionBoundaryService.digestRun(run) } }); } catch (error: any) { return fail(res, error); } });
router.get('/releases', (req, res) => { if (!validateTenantRequest(req, res)) return; return res.json({ status: 'success', releases: ReleaseService.list(tenant(req)), current: ReleaseService.current(tenant(req)) ?? null }); });
router.post('/jobs/:id/release', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.status(201).json({ status: 'success', release: ReleaseService.deploy(tenant(req), req.params.id) }); } catch (error: any) { return fail(res, error); } });
router.post('/releases/rollback', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.json({ status: 'success', release: ReleaseService.rollback(tenant(req), req.body.releaseId) }); } catch (error: any) { return fail(res, error); } });
router.get('/failures', (req, res) => { if (!validateTenantRequest(req, res)) return; return res.json({ status: 'success', failures: FailureService.list(tenant(req)) }); });
router.post('/failures', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.status(201).json({ status: 'success', failure: FailureService.record({ ...req.body, tenantId: tenant(req) }) }); } catch (error: any) { return fail(res, error); } });
router.post('/failures/:id/retry', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.json({ status: 'success', failure: FailureService.retry(tenant(req), req.params.id) }); } catch (error: any) { return fail(res, error); } });
router.post('/failures/:id/resolve', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.json({ status: 'success', failure: FailureService.resolve(tenant(req), req.params.id, req.body.evidence) }); } catch (error: any) { return fail(res, error); } });
router.get('/outcomes', (req, res) => { if (!validateTenantRequest(req, res)) return; return res.json({ status: 'success', outcomes: OutcomeService.list(tenant(req)), summary: OutcomeService.summary(tenant(req)) }); });
router.post('/outcomes', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.status(201).json({ status: 'success', outcome: OutcomeService.record({ ...req.body, tenantId: tenant(req) }) }); } catch (error: any) { return fail(res, error); } });
router.get('/autonomy', (req, res) => { if (!validateTenantRequest(req, res)) return; return res.json({ status: 'success', sessions: AutonomyService.list(tenant(req)) }); });
router.post('/autonomy', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.status(201).json({ status: 'success', session: AutonomyService.start({ ...req.body, tenantId: tenant(req) }) }); } catch (error: any) { return fail(res, error); } });
router.post('/autonomy/:id/consume', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.json({ status: 'success', session: AutonomyService.consume(tenant(req), req.params.id, req.body.action, req.body.costUnits) }); } catch (error: any) { return fail(res, error); } });
router.post('/autonomy/:id/abort', (req, res) => { if (!validateTenantRequest(req, res)) return; try { return res.json({ status: 'success', session: AutonomyService.abort(tenant(req), req.params.id) }); } catch (error: any) { return fail(res, error); } });
export default router;
